import os
import argparse
import pandas as pd
import numpy as np
from sklearn.decomposition import TruncatedSVD

'''
Script that computes PoN using SVD and WGS matrix from prior step
To Add:
Log file instead of print statements

python3 WGS2PoN.py --wgs_matrix ../CCLE_WXS/WES2WGS_CCLE/1000genomes_10wgs_normals_matrix.tsv --output ../CCLE_WXS/1000genomes_highcov_WGS/PoN_1000genomes_wgs_normals.tsv
'''

def main():
    # ----------------------------------------------------
    # 1. PARAMETERS & INPUT PATHS
    # ----------------------------------------------------
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--wgs_matrix", metavar="FILE", required=True,
                   help="GC corrected WGS counts per genomic window matrix")
    p.add_argument("-k", metavar="INT", type=int,
                   default=5, help="K determines top components to strip in SVD")
    p.add_argument("--output", metavar="FILE", required=True,
                   help="PoN from WGS samples using SVD (GATK style)")
    # Add an argument to look for the scales file
    p.add_argument("--wgs_matrix", metavar="FILE", required=True,
                   help="GC corrected WGS counts per genomic window matrix")
    # ... (keep other arguments the same) ...
    args = p.parse_args()

    INPUT_MATRIX_TSV = args.wgs_matrix
    SCALES_FILE = INPUT_MATRIX_TSV + ".scales" # Auto-detect companion file
    
    # SVD Tuning Parameter
    # K determines how many top components (systematic technical noise/batch effects) to strip.
    # K=2 to 5 is typical for smaller or highly uniform cohorts; K=10 to 20 for large/noisy batches.
    N_COMPONENTS_TO_REMOVE = args.k
    
    # Output File
    PON_OUTPUT_TSV = args.output

    if not os.path.exists(INPUT_MATRIX_TSV):
        print(f"[-] Error: Input matrix file '{INPUT_MATRIX_TSV}' not found.")
        return

    print(f"[+] Loading GC-corrected WGS matrix: {INPUT_MATRIX_TSV}")
    # Read matrix; preserve coordinate data
    df_matrix = pd.read_csv(INPUT_MATRIX_TSV, sep='\t', index_col=0)
    
    # Separate metadata columns from the actual depth numbers
    meta_cols = ['chrom', 'start', 'end', 'gc_pct']
    sample_cols = [col for col in df_matrix.columns if col not in meta_cols]
    
    W = df_matrix[sample_cols].values  # Shape: (n_windows, n_samples)
    n_windows, n_samples = W.shape
    
    print(f"    -> Matrix dimensions: {n_windows} windows x {n_samples} samples.")
    
    if n_samples < 2:
        print("[-] Error: SVD denoising requires at least 2 or more sample columns to model covariance.")
        return
        
    if N_COMPONENTS_TO_REMOVE >= n_samples:
        N_COMPONENTS_TO_REMOVE = max(1, n_samples - 1)
        print(f"[!] Warning: K components cannot exceed sample size. Auto-adjusting K to: {N_COMPONENTS_TO_REMOVE}")

    # ----------------------------------------------------
    # 2. STEP 4.1: CENTER PER-WINDOW MEAN
    # ----------------------------------------------------
    print("[+] Centering data: Computing and subtracting per-window mean values...")
    window_means = np.mean(W, axis=1, keepdims=True)
    W_centered = W - window_means

    # ----------------------------------------------------
    # 3. STEP 4.2: COMPUTE SVD & REMOVE TOP K COMPONENTS
    # ----------------------------------------------------
    print(f"[+] Computing Singular Value Decomposition (SVD) to isolate top {N_COMPONENTS_TO_REMOVE} batch components...")
    
    # We use TruncatedSVD to capture the top components capturing the strongest systematic variances
    svd = TruncatedSVD(n_components=N_COMPONENTS_TO_REMOVE, random_state=42)
    
    # Fit and transform the data: 
    # U_sigma represents the projection of windows onto the batch space
    U_sigma = svd.fit_transform(W_centered) # Shape: (n_windows, K)
    V_T = svd.components_                   # Shape: (K, n_samples)
    
    # Calculate total explained variance caught by the noise components
    explained_variance_pct = np.sum(svd.explained_variance_ratio_) * 100
    print(f"    -> Top {N_COMPONENTS_TO_REMOVE} components explain {explained_variance_pct:.2f}% of systematic variance.")

    # Reconstruct exclusively the bias matrix generated by those K components
    W_bias = np.dot(U_sigma, V_T)

    # Denoise the data: Subtract the captured batch bias matrix from our centered matrix
    W_denoised_centered = W_centered - W_bias
    
    # Add back the window means to return to original depth scale space
    W_denoised = W_denoised_centered + window_means
    
    # ----------------------------------------------------
    # NEW STEP: PROJECT DENOISED MATRIX TO TRUE RAW DEPTH
    # ----------------------------------------------------
    if os.path.exists(SCALES_FILE):
        print(f"[+] Found raw depth scales profile: {SCALES_FILE}")
        scales_df = pd.read_csv(SCALES_FILE, sep='\t', header=None, index_col=0)
        # Ensure sample column ordering matches matrix exactly
        raw_medians = [scales_df.loc[col].values[0] for col in sample_cols]
        raw_medians = np.array(raw_medians)
        
        # Multiply each sample column back by its original absolute baseline
        W_denoised_raw = W_denoised * raw_medians
    else:
        print(f"[!] Warning: Scales file missing at {SCALES_FILE}. Defaulting to absolute 30x fallback.")
        W_denoised_raw = W_denoised * 30.0

    # ----------------------------------------------------
    # 4.3: COMPUTE FINAL PoN MEDIAN & VARIANCE (ON RAW SCALE)
    # ----------------------------------------------------
    print("[+] Generating Panel of Normals (PoN) absolute tracking statistics...")
    
    # These metrics are now in absolute read counts (e.g. ~30x, varying by window)!
    pon_median = np.median(W_denoised_raw, axis=1)
    pon_variance = np.var(W_denoised_raw, axis=1)

    # ----------------------------------------------------
    # 5. ASSEMBLE AND SAVE THE TARGET PoN TRACK
    # ----------------------------------------------------
    print("[+] Merging statistics into final track table layout...")
    
    pon_df = df_matrix[meta_cols].copy()
    pon_df['pon_median'] = pon_median
    pon_df['pon_variance'] = pon_variance
    
    # Set up a strict filtering flag recommendation column 
    # Flag windows in the top 1% highest variance bracket as potentially volatile
    variance_threshold = np.percentile(pon_variance, 99)
    pon_df['is_high_variance'] = (pon_variance > variance_threshold).astype(int)
    
    print(f"    -> Flagged {pon_df['is_high_variance'].sum()} windows exceeding 99th percentile variance threshold ({variance_threshold:.4e})")

    # Export
    pon_df.to_csv(PON_OUTPUT_TSV, sep='\t', index=True)
    
    print("\n" + "="*60)
    print(f"[+] STEP 4 COMPLETE!")
    print(f"    -> SVD Denoised PoN saved to: {PON_OUTPUT_TSV}")
    print(f"    -> Track Head:\n{pon_df[['chrom', 'pon_median', 'pon_variance', 'is_high_variance']].head()}")
    print("="*60)

if __name__ == "__main__":
    main()